# Default values for cronjob.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.io/aliaksxssv/attack-simulation
  tag: data_exfiltration_amd64
  imagePullPolicy: Always
  imagePullSecret: ""

labels:
  app: attack-simulation-data-exfiltration

schedule: "*/5 * * * *"
command: ["/bin/bash"]
args:
  - "/opt/attack_simulation/data_exfiltration.sh"
env: []

resources: 
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

securityContext: {}

#securityContext:
#  capability: SYS_ADMIN
#  privileged: true

annotations: {}
startingDeadlineSeconds: 240
failedJobsHistoryLimit: 5
successfulJobsHistoryLimit: 3
concurrencyPolicy: Forbid
restartPolicy: Never
backoffLimit: 3
nodeSelector: {}
tolerations: []

serviceAccount:
  create: false
  name: ""
  annotations: []

clusterRole:
  name: ""

clusterRoleBinding:
  name: ""

volume:
  mountPath: ""

configMap:
  config: {}

secrets: {}