{{- if (gt (len .Values.configMap.config) 0) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cronjob.fullname" . }}
  labels:
    {{- include "cronjob.labels" . | nindent 4 }}
{{- with .Values.configMap.config }}
data:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
