{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cronjob.fullname" . }}
  labels:
    {{- include "cronjob.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $k, $v := .Values.secrets }}
  {{- if kindIs "map" $v }}
  {{ $k }}: {{ $v | toJson | b64enc | quote }}
  {{- else if kindIs "slice" $v }}
  {{ $k }}: {{ $v | toJson | b64enc | quote }}
  {{- else }}
  {{ $k }}: {{ $v | toString | b64enc | quote }}
  {{- end }}
{{- end }}
{{ end }}
